JOIN_TIMEOUT = 3.0
HEARTBEAT_INTERVAL = 0.1
QUEUES_MAXSIZE = 8
INGRESS_FPS = 30
MOTION_NUM_STEPS = 1

WRIST_MOTOR_IDX = 16
DEFAULT_PORT = 50051
DEFAULT_HAND = "right"

# MediaPipe teleop
DEFAULT_CONFIDENCE = 0.7
_NUM_KEYPOINTS = 21
_COORDS_PER_POINT = 3
_EXPECTED_LEN = _NUM_KEYPOINTS * _COORDS_PER_POINT

# Meta Quest teleop
WORKSPACE_HALF_BOX_M = (0.212, 0.226, 0.142)
AUTO_FIT_MARGIN = 0.7
CUTOFF_MIN = 0.05

MIN_SPAN_SAMPLES = 150
SPAN_BUFFER_SECONDS = 60.0
SPAN_REFIT_PERIOD_S = 60.0
SPAN_CHANGE_THRESHOLD = 0.10
BOOTSTRAP_SCALE = 0.15

STILL_THRESHOLD_M = 0.01
STILL_WINDOW_SAMPLES = 30
CLUTCH_GRACE_S = 2.0
