# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from orca_teleop.ingress import hand_stream_pb2 as orca__teleop_dot_ingress_dot_hand__stream__pb2


class HandStreamStub(object):
    """The single service that all publishers implement.
    Robot side runs the server; publishers connect as clients and stream frames.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamHandFrames = channel.stream_unary(
                '/orca_teleop.HandStream/StreamHandFrames',
                request_serializer=orca__teleop_dot_ingress_dot_hand__stream__pb2.HandFrame.SerializeToString,
                response_deserializer=orca__teleop_dot_ingress_dot_hand__stream__pb2.StreamSummary.FromString,
                )


class HandStreamServicer(object):
    """The single service that all publishers implement.
    Robot side runs the server; publishers connect as clients and stream frames.
    """

    def StreamHandFrames(self, request_iterator, context):
        """Publisher opens a stream and continuously sends HandFrames.
        The robot responds with a summary when the stream closes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamHandFrames': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamHandFrames,
                    request_deserializer=orca__teleop_dot_ingress_dot_hand__stream__pb2.HandFrame.FromString,
                    response_serializer=orca__teleop_dot_ingress_dot_hand__stream__pb2.StreamSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orca_teleop.HandStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HandStream(object):
    """The single service that all publishers implement.
    Robot side runs the server; publishers connect as clients and stream frames.
    """

    @staticmethod
    def StreamHandFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/orca_teleop.HandStream/StreamHandFrames',
            orca__teleop_dot_ingress_dot_hand__stream__pb2.HandFrame.SerializeToString,
            orca__teleop_dot_ingress_dot_hand__stream__pb2.StreamSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
