# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manus_stream.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12manus_stream.proto\x12\x05proto\"%\n\x05Stamp\x12\x0b\n\x03sec\x18\x01 \x01(\x05\x12\x0f\n\x07nanosec\x18\x02 \x01(\x05\"7\n\x06Header\x12\x1b\n\x05stamp\x18\x01 \x01(\x0b\x32\x0c.proto.Stamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\"+\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"8\n\nQuaternion\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"Q\n\x04Pose\x12!\n\x08position\x18\x01 \x01(\x0b\x32\x0f.proto.Position\x12&\n\x0borientation\x18\x02 \x01(\x0b\x32\x11.proto.Quaternion\"x\n\nGloveState\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.proto.Header\x12$\n\x0fleft_mocap_pose\x18\x02 \x03(\x0b\x32\x0b.proto.Pose\x12%\n\x10right_mocap_pose\x18\x03 \x03(\x0b\x32\x0b.proto.Poseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manus_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STAMP']._serialized_start=29
  _globals['_STAMP']._serialized_end=66
  _globals['_HEADER']._serialized_start=68
  _globals['_HEADER']._serialized_end=123
  _globals['_POSITION']._serialized_start=125
  _globals['_POSITION']._serialized_end=168
  _globals['_QUATERNION']._serialized_start=170
  _globals['_QUATERNION']._serialized_end=226
  _globals['_POSE']._serialized_start=228
  _globals['_POSE']._serialized_end=309
  _globals['_GLOVESTATE']._serialized_start=311
  _globals['_GLOVESTATE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
